-- Create gallery table
create table if not exists gallery (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  category text check (category in ('karya', 'event', 'prestasi')) not null,
  image_url text,
  event_date date,
  time text,
  location text,
  author_name text,
  author_age integer,
  participants text,
  year text,
  icon text,
  tags text[],
  is_featured boolean default false,
  is_published boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table gallery enable row level security;

-- Drop existing policy if it exists
DROP POLICY IF EXISTS "Allow public read access to published gallery items" ON gallery;

-- Create policy to allow public read access to published items
create policy "Allow public read access to published gallery items"
on gallery for select
to anon
using (is_published = true);

-- Create index on category for better performance
create index if not exists gallery_category_idx on gallery (category);

-- Create index on is_published for better performance
create index if not exists gallery_is_published_idx on gallery (is_published);

-- Create index on created_at for better performance
create index if not exists gallery_created_at_idx on gallery (created_at);